---
title: "Nicholas Corzine's resume"
author: Nicholas Corzine
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================



Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> corzinen@gmail.com
- <i class="fa fa-github"></i> [github.com/corzinen](https://github.com/corzinen)
- <i class="fa fa-linkedin"></i> [linkedin.com/in/corzinen](https://www.linkedin.com/in/corzinen/)
- <i class="fa fa-phone"></i> +1 000-000-0000
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Risk management

- Ethical decision-making

- Mitigation strategy development 

- Business continuity

- Statistical analysis

- R, SQL, Bash/Shell, Git, Excel, Power BI

Certifications {#certifications}
--------------------------------------------------------------------------------

CISSP - ISC2 | Credential ID: 485075

Open FAIR™ Certification Program - The Open Group | Candidate ID: 365566


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Nicholas Corzine {#title}
--------------------------------------------------------------------------------

As an experienced Risk Management professional with 15 years of expertise in 
Information Technology, Security Risk Management, and data protection, I bring 
a wealth of knowledge and leadership qualities to any organization. I am a 
success-driven individual, constantly seeking new ways to improve operational
efficiencies and drive growth through strategic planning and implementation.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Bellevue University

Bachelor of Science, Computer Information Systems

Bellevue, NE

2012

### Missouri State University

Master of Business Administration, Quantitative Enterprise Risk Management

Springfield, MO

2025
  

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Director Cybersecurity Risk and Governance

MiTek Inc. 

Chesterfield, MO

Present - May 2023

::: concise
Oversee development and execution of MiTek's global Cybersecurity GRC strategy, Policy Lifecycle Management, Issue Management, Risk and Compliance Analytics, Security Awareness and Training, Business Continuity Management, Vendor Risk Management, Data Protection, and Insider Risk Management.
:::

### Cybersecurity Consultant

Dell Technologies 

Remote

April 2022

::: concise
Collaborated on the development and execution of the Integrated Risk Management strategy. Key responsibilities included driving informed risk-based decision-making by collaborating with cross-functional security teams and business unit representatives and providing strategic and operational security risk consultation.
:::

### Manager, Cyber Risk Quantification

Centene Corporation

Clayton, MO

May 2019

::: concise
I managed a team in developing and implementing advanced analytic strategies and decision support systems
for Centene's Enterprise Cybersecurity and Security Risk Management. These efforts were crucial in predicting
cyber losses, devising mitigation strategies, and providing vital information for Board of Director reporting
and cyber liability policy decisions.
:::

### Manager, Information Security Governance and Risk

Emerson Electric

St. Louis, MO

November 2017

::: concise
I was responsible for enterprise-wide information security policy and standard lifecycle management and IT
security risk management activities, including Third-Party and Supply Chain Cyber Risk Management. I led a
team positioned globally to ensure the security program aligned with industry regulations and security
frameworks, including ISO 27001, GDPR, DFARS, and NIST 800-171.
:::

### Lead Information Security Risk Specialist

Emerson Electric

St. Louis, MO

2015

### Information System Security Manager

Boeing

St. Louis, MO

2012

### Systems Engineer

Northrup Grumman

San Diego, CA

2010

### Information Assurance Systems Analyst

Accenture

San Diego, CA

2008

### Information Systems Technician

US Navy

San Diego, CA

2004


Professional Contributions {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Co-Chair

St. Louis FAIR Institute Chapter

St. Louis, MO

2021 - 2020

::: concise
Collaborated with industry peers to establish a local chapter dedicated to advancing the understanding and
implementation of Factor Analysis of Information Risk (FAIR) principles. Focused on fostering a community of
cybersecurity and risk management professionals, the chapter aimed to facilitate knowledge sharing, best
practices, and collaborative initiatives to elevate cyber risk management standards in the St. Louis region.
Engaged in organizing events, workshops, and discussions to promote the adoption of FAIR methodologies
and enhance the overall cybersecurity resilience of organizations within our community.
:::

#### Presenter: A Probabilistic Approach to Third-Party Risk Management

--- SiRACon, 2021

#### Co-Presenter: Presenting Metrics to the Board

--- FAIR Institute Global Chapter Meeting, 2020

#### Contributing Author: "Cyber Risk Oversight 2020, Key Principles and Practical Guidance for Corporate Boards". 

--- National Association of Corporate Directors and the Internet Security Alliance.
